ethz-asl/data-driven-dynamics

- Tools/parametric_model/generate_parametric_model.py
This way the user and automated tests can run without needing to install the dependencies of the visual dataframe selector.
> Only import visual dataframe selection when data selection is enabled

- Tools/parametric_model/src/models/multirotor_model.py
As reported in https://github.com/ethz-asl/data-driven-dynamics/issues/180, plotting has been failing with the following error
```
Traceback (most recent call last):
File "Tools/parametric_model/generate_parametric_model.py", line 117, in <module>
start_model_estimation(**vars(arg_list))
File "Tools/parametric_model/generate_parametric_model.py", line 99, in start_model_estimation
model.compute_residuals()
File "/home/jaeyoung/dev/data-driven-dynamics/Tools/parametric_model/src/models/dynamics_model.py", line 487, in compute_residuals
error_y_moments = y_moments_pred - self.y_moments
AttributeError: 'MultiRotorModel' object has no attribute 'y_moments'
Makefile:35: recipe for target 'estimate-model' failed
make: *** [estimate-model] Error 1
```
This is a quick WIP …
> Make plotting happy by adding moments member

- .github/workflows/sysid_test.yml
- Makefile
- README.md
- Tools/parametric_model/src/models/dynamics_model.py
Plotting of the predictions were broken as reported in https://github.com/ethz-asl/data-driven-dynamics/issues/180
This was due to the fact that the axis order of the prediction / measurement has been flipped after https://github.com/ethz-asl/data-driven-dynamics/pull/176
This PR fixes the plotting by fixing the order of the matrices
**Testing**
The results can be reproduced with the following command.
```
make estimate-model plot=True
```
**Before PR**
**After PR**
**Additional Context**
- This is a follow up of https://github.com/ethz-asl/data-driven-dynamics/pull/181
- Fixes https://github.com/ethz-asl/data-driven-dynamics/issues/180
> Fix plotting

- Tools/parametric_model/generate_parametric_model.py
From the discussion we had in https://github.com/ethz-asl/data-driven-dynamics/pull/186, my understanding was that we wanted the automatic data selection disabled by default
However, it was enabled by default, and resulting in the following failure
```
Traceback (most recent call last):
File "Tools/parametric_model/generate_parametric_model.py", line 146, in <module>
start_model_estimation(**vars(arg_list))
File "Tools/parametric_model/generate_parametric_model.py", line 128, in start_model_estimation
model.compute_residuals()
File "/home/jaeyoung/dev/data-driven-dynamics/Tools/parametric_model/src/models/dynamics_model.py", line 486, in compute_residuals
y_forces_pred[0::3] = y_pred[0:int(self.y_forces.shape[0]/3)]
ValueError: could not broadcast input array from …
```
> Disable auto data selection

- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/multirotor_model.py
This is a fix for the issue that arises when plotting and manual data selection is performed. The issue stems from the self.y_forces and self.y_moments not being cropped during data selection which leads to wrong sizes during plotting. This pr fixes the issue by correctly passing cropped y_forces and y_moments to the residual calculation and plotting.
> Fix plotting with dataselection

- Tools/parametric_model/src/models/dynamics_model.py
Plotting was broken in https://github.com/ethz-asl/data-driven-dynamics/pull/191 with the reshuffling of the axis ordering
To reproduce:
```
make estimate model
```
- Before PR: 
- After PR:
**Alternatives**
We could change the default ordering for the plotting, but should be good this way for now.
**Additional Context**
- Fixes https://github.com/ethz-asl/data-driven-dynamics/issues/192
> Fix plotting (Again)

- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/model_plots/linear_model_plots.py
This commit turns off the annotation and uses a tight layout for the plots
- Before PR
- After PR
**Additional Context**
- Fixes https://github.com/ethz-asl/data-driven-dynamics/issues/167
> Turn off annotations for the covariance visualization

- .github/workflows/sysid_test.yml
- Tools/parametric_model/configs/standardplane_model.yaml
- Tools/parametric_model/src/models/__init__.py
- Tools/parametric_model/src/models/aerodynamic_models/control_surface_model.py
- Tools/parametric_model/src/models/aerodynamic_models/standard_wing_model.py
- Tools/parametric_model/src/models/standardplane_model.py
This is a WIP PR for adding support for fixedwing models for the data driven dynamics pipeline
- Added standard wing model
- Added aero control surface model
**Testing**
```
make estimate-model model=standardplane_model
```
**Discussion**
Since fixedwing models never stall in the log, the stall parameters are largely unobservable throughout the log.
This is correctly reported by the pipeline:
```
/home/jaeyoung/dev/data-driven-dynamics/Tools/parametric_model/src/optimizers/optimizer_base_template.py:79: RuntimeWarning: Feature detected that is only zero. Parameter c_d_wing_xz_fp_min is probably wrong.
RuntimeWarning
/home/jaeyoung/dev/data-driven-dynamics/Tools/parametric_model/src/optimizers/optimizer_base_template.py:79: RuntimeWarning: Feature detected that is …
```
> Add support for fixed wing models

- Tools/parametric_model/configs/dynamics_model_test_config.yaml
- Tools/parametric_model/configs/quadrotor_model.yaml
- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/tools/data_handler.py
- Tools/parametric_model/src/tools/dataframe_tools.py
- Tools/parametric_model/src/tools/ulog_tools.py
uORB topics support [multi instance publishing](https://docs.px4.io/v1.12/en/middleware/uorb.html#multi-instance), however this pipeline does not consider this and always default to `id = 0`
This is a problem with the recent control allocation added in PX4 where `actuator_outputs` essentially are published by multiple entitites and therefore published on different channels
**Proposed Solution**
This commit adds support for multi ID uorb topics. The ID of the topic can be now specified in the configuration file when specifying uORB topics
```
data:
required_ulog_topics:
actuator_outputs:
id: 0
```
**Additional Context**
- Fixes https://github.com/ethz-asl/data-driven-dynamics/issues/196
> Add support for multi ID topics

- Tools/parametric_model/src/tools/data_handler.py
- Tools/parametric_model/src/tools/dataframe_tools.py
When having multi id topics, and if the instance zero topic is missing, the pipeline would fail to find the required topic
```
===============================================================================
Data Processing                                  
===============================================================================
Initializing of configuration successful. 
Resample frequency:  250.0 Hz
Loading uLog file:  /home/jaeyoung/Downloads/4a1e0d54-d44f-443a-989b-f135f392ef6b.ulg
Loading topics:
actuator_outputs
vehicle_local_position
vehicle_attitude
vehicle_angular_velocity
sensor_combined
Missing topic type:  actuator_outputs
Makefile:34: recipe for target 'estimate-model' failed
make: *** [estimate-model] Error 1
```
**Proposed Solution**
Handle the …
> Support mutli ID topics when checking for required topics

- Tools/parametric_model/src/models/aerodynamic_models/__init__.py
- Tools/parametric_model/src/models/aerodynamic_models/phiaerodynamics_model.py
- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/model_plots/aerodynamics_plots.py
This PR implements the global singularity-free aerodynamics model for fixed wing models.
```
Lustosa, Leandro R., François Defaÿ, and Jean-Marc Moschetta. "Global singularity-free aerodynamic model 
for algorithmic flight control of tail sitters." 
Journal of Guidance, Control, and Dynamics 42.2 (2019): 303-316.
```
The model can be tested by using the following command
```
make estimate-model model=standardplane_model
```
- Estimated parameters:
```
phifv_11: 0.05242144970545798
phifv_12: 0.0031738994763961382
phifv_13: 0.07187260507287652
phifv_21: 0.004374913338620598
phifv_22: 0.2614765087511536
phifv_23: 0.06354479622908615
phifv_31: 0.08597274480112282
phifv_32: 0.03291630360628932
phifv_33: 0.9735012828891294
```
- Cramer-Rao bounds for the aerodynamics model:
```
phifv_11 …
```
> Implementation of Global Singularity-free aerodynamics model

- README.md
- Tools/parametric_model/configs/config_template.yaml
- Tools/parametric_model/configs/dynamics_model_test_config.yaml
- Tools/parametric_model/configs/fixedwing_longitudinal_model.yaml
- Tools/parametric_model/configs/quadplane_model.yaml
- Tools/parametric_model/configs/quadrotor_model.yaml
- Tools/parametric_model/configs/vtol_tiltrotor_longitudinal_model.yaml
- Tools/parametric_model/generate_parametric_model.py
- Tools/parametric_model/src/models/__init__.py
- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/extractor_models/__init__.py
- Tools/parametric_model/src/models/extractor_models/fixedwing_extractor_model.py
- Tools/parametric_model/src/models/model_config.py
- Tools/parametric_model/src/models/rotor_models/linear_rotor_model.py
- Tools/parametric_model/src/tools/dataframe_tools.py
This pull request adds another part to the pipeline, which allows users to directly extract many PX4 parameters for longitudinal control & stability from the identified model.
Note: The identified coefficients go beyond what is currently used in PX4, but some of them might be helpful for further development in the area model-based control. A more detailed list can be found in the updated README of the repository.
```
python3 Tools/parametric_model/generate_parametric_model.py --config Tools/parametric_model/configs/vtol_tiltrotor_longitudinal_model.yaml LOGFILE --normalization False --plot False --extraction True
```
> extractor: Implement PX4 parameter extraction for fixed wing models

- README.md
- Tools/parametric_model/configs/fixedwing_singularityfree_model.yaml
- Tools/parametric_model/generate_parametric_model.py
- Tools/parametric_model/src/models/__init__.py
- Tools/parametric_model/src/models/aerodynamic_models/phiaerodynamics_model.py
- Tools/parametric_model/src/models/extractor_models/__init__.py
- Tools/parametric_model/src/models/extractor_models/fixedwing_extractor_model.py
- Tools/parametric_model/src/models/extractor_models/singularityfree_extractor_model.py
- Tools/parametric_model/src/models/global_singularityfree_model.py
Until now, the global singularity-free model implemented for this pipeline was only usable with manual code modifications. 
**Proposed Solution**
- This pull request adds a separate config file `fixedwing_singularityfree_model.yaml`, which takes care of the correct setup for fixed wing flight logs.
- A corresponding extractor for PX4 parameters (as described in the README of the repository) was added for the global singularity-free model.
To apply it to fixedwing logs:
`python3 Tools/parametric_model/generate_parametric_model.py --config Tools/parametric_model/configs/fixedwing_singularityfree_model.yaml ULOG_FILE --normalization False --extraction True`
> enhance: add config and extractor for global-singularity free approach

- Tools/parametric_model/generate_parametric_model.py
For interactive data selection, required topics are hard coded as `u1`, `u2`, `u3`, `u4`, and therefore makes the whole data selection fail if the topics are missing.
```
-------------------------------------------------------------------------------
Initialized dataframe with the following columns: 
['timestamp', 'u0', 'u1', 'u3', 'u4', 'u6', 'vx', 'vy', 'vz', 'q0', 'q1', 'q2', 'q3', 'ang_vel_x', 'ang_vel_y', 'ang_vel_z', 'ang_acc_b_x', 'ang_acc_b_y', 'ang_acc_b_z', 'acc_b_x', 'acc_b_y', 'acc_b_z', 'aux1', 'throttle', 'aileron', 'elevator', 'rudder', 'landed']
Data contains  37240 timestamps.
Computing force features for rotor
Computing moment features for rotor
Feature Computation |############################### | 37239/37240
Starting computation of aero moment …
```
> Fix interactive data selection when u2 is missing

- Tools/parametric_model/src/tools/data_handler.py
- Tools/parametric_model/src/tools/dataframe_tools.py
**Problem Description:**
This PR addresses the problem described in issue #223. The flight time extraction step was limited to cases where the log only contains a single flight. This might cause problems, if the landed topic deviates from the `landed` state for example due to bumps on landing.
**Proposed Solution:**
The implementation of the flight time computation has been modified to work with an arbitrary number of flights in a single log. All flight segments will simply be concatenated.
>  enhance: change flight time extraction to be able to detect multiple flight segments in single log file

- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/model_plots/aerodynamics_plots.py
While the lift drag curve visualization is quite useful to see what the identified aerodynamics model looks like, a lot of the curve is actually extrapolating from measured data.
This PR visualizes the data points of angle of attack on the curve to visualize which data is being used for the extrapolation.
**Note**
Note that the measurements are perfectly "on the curve" since only the measured angle of attack is being used and the identified model is used to compute `c_l` and `c_d`. This should be replaced by "measured" `c_l` and `c_d` in a future PR
**Testing**
- log: https://review.px4.io/plot_app?log=a967d7a5-10fa-41ca-b43a-1abaebce044a (from https://github.com/ethz-asl/data-driven-dynamics/issues/224)
```
make estimate-model model=fixedwing_model …
```
> Visualize data points in the liftdrag plot

- Tools/parametric_model/src/models/dynamics_model.py
- Tools/parametric_model/src/models/model_plots/aerodynamics_plots.py
This is a follow up PR of https://github.com/ethz-asl/data-driven-dynamics/pull/227
Visualize uncertainty of the identified lift drag model, based on the Cramer-Rao bounds
- Linear Liftdrag
- $\Phi$ - Aerodynamics
> Visualize uncertainty in liftdrag plot

- Makefile
- README.md
- Tools/parametric_model/configs/config_template.yaml
- Tools/parametric_model/configs/dynamics_model_test_config.yaml
- Tools/parametric_model/configs/fixedwing_model.yaml
- Tools/parametric_model/configs/fixedwing_singularityfree_model.yaml
- Tools/parametric_model/configs/quadplane_model.yaml
- Tools/parametric_model/configs/quadrotor_model.yaml
- Tools/parametric_model/configs/vtol_tiltrotor_model.yaml
- Tools/parametric_model/generate_parametric_model.py
- Tools/parametric_model/src/models/model_config.py
- Tools/parametric_model/src/tools/data_handler.py
**Problem Description:**
Until now, it was only possible to select data based on one of the 6 available `manual_control_setpoint` topics `aux1` to `aux6` when using the `data_selection=setpoint` option. It was requested that this mechanism should be more flexible and also accept other variables more flexibly.
**Proposed Solution:**
In addition to the `data_selection` attribute, the user can now provide a `selection_var` variable to the `make` command (with the syntax `topic_name/variable_name` - e.g. `manual_control_setpoint/aux1`). The corresponding variable will then be added to the topics that are loaded from the log file and used to identify relevant sections of the provided log.
Test command:
```
make estimate-model model=fixedwing_model log=path_to_ulog data_selection=setpoint …
```
> enhance: allow data selection with arbitrary setpoint topics and variables

- .github/workflows/build_test.yml
- .github/workflows/sysid_test.yml
- .gitmodules
- Tools/parametric_model/requirements.txt
The Visual Pandas selector is now available as an official python package on PyPi. Therefore i suggest removing the submodule and just installing it regularly like all the other python dependencies.
> Remove vpselector submodule and add as pypi dependency

- Tools/parametric_model/predict_model.py
- Tools/parametric_model/src/models/dynamics_model.py
**Problem Description:**
This pull request addresses the problems described in #233. The prediction command does not work at the moment.
**Proposed Solution:**
The prediction script and/or the correspondingly used functions therein have been adapted to use the interfaces, which the estimation tasks also use. Additionally, only the model results and no fisher information is logged to resolve corresponding errors.
> fix: ensure that model prediction with makefile command works as expected

- .github/workflows/sysid_test.yml
- Makefile
- README.md
Removed depreciated make install-full-dependencies since the vpselector is not just a pip package in requirements.txt
> Fix Ci pipeline
